prngs-master/config/routes.rb
Prngs::Application.routes.draw do

  root :to => "home#index"
  
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  match "/login", to: "sessions#new", :as => "login"
  match "/logout", to: "sessions#destroy", :as => "logout"

  match "/auth/:provider/callback", to: "sessions#create"
  match "/auth/failure", to: "sessions#failure"

  post "/deauth/:provider", to: "users#deauth", :as => "deauth"

  resources :users

  resources :sources

  resources :mentions

  resources :artists

  resources :videos do
    get :autocomplete_video_and_sources_and_artists_search, :on => :collection
  end

  post "/search", to: "searches#search", :as => "search"
end

prngs-master/app/models/source.rb
class Source < ActiveRecord::Base

  has_many :mentions

  validates_presence_of :name
  validates_uniqueness_of :name

  serialize :feeds

  include NamedScopes::DateTime
  include NamedScopes::Popularity

  searchable do
    text    :name
    integer :popularity
    integer :mentions do
      mentions.map(&:video).compact.count
    end
    time    :created_at
  end


  def videos
    mentions.map(&:video).compact.uniq
  end

  def relevance
    videos.count > 0 ? popularity.to_i + (videos.count*10) : 0
  end

  def self.most_relevant
    Source.all.delete_if{|s| s.relevance == 0}.sort_by(&:relevance).reverse
  end

  def self.primary_search(query)
    Source.solr_search do
      fulltext query
      order_by :created_at, :desc
      order_by :popularity, :desc
      order_by :mentions, :desc
      paginate :per_page => 10
    end
  end

  def self.construct(name, url, kind)
    if source = Source.find_by_name(name)
      source
    else
      source = Source.create(
                 :name => name,
                 :url => url,
                 :kind => kind
               )
      BeanCounter.rank(source)
      source
    end
  end
end

prngs-master/app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  
  def index
    @sources = Source.all
  end

  def show
    @source = Source.find(params[:id])
    @videos = Kaminari.paginate_array(@source.videos).page(params[:page]).per(10)
    @mentions = Mention.where{source == @source && text.length > 5 && video_id != nil}.from_last(1.year).random(3).uniq
  end
end

prngs-master/app/helpers/sources_helper.rb
module SourcesHelper
end

prngs-master/app/views/sources/_source.html.haml
%li.source.thumb.entity
  .meta
    %h3= link_to source.name, source_path(source)
  .loading

prngs-master/app/views/sources/_thumb.html.haml
%li.source.thumb.entity
  .meta
    %h3= link_to source.name, source_path(source)
  .loading

prngs-master/app/views/sources/_videos.html.haml
%ul.media-list.source
  = render :collection => @videos, :as => :video, :partial => "videos/thumb"

  = paginate @videos, :id => "pagination"

prngs-master/app/views/sources/index.html.haml
= content_for_or_pjax :heading do
  %h1 Sources

prngs-master/app/views/sources/show.html.haml
= render @source

= render "mentions/mentions"

= render "sources/videos"